name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.9'

      - name: Update Julia Registries
        run: julia -e 'using Pkg; Pkg.Registry.update()'

      - name: Install Dependencies
        run: julia --project -e 'using Pkg; Pkg.instantiate(); Pkg.resolve(); Pkg.precompile()'

      - name: Add Coverage Dependency
        run: julia --project -e 'using Pkg; Pkg.add("Coverage")'

      - name: Run Tests and Generate Coverage
        run: |
          julia --project -e '
            using Pkg;
            Pkg.develop(path="."); # Ensures local package is available
            Pkg.instantiate();
            Pkg.add(["Test", "POMDPs", "POMDPTools", "Random", "GapHeuristicSearch"]);
            Pkg.precompile()'

      - name: Run tests
        run: julia --project=. -e '
          using Pkg;
          Pkg.activate(".");
          Pkg.test()'
